### ISSUE TITLE
Query string arguments not supported in makePath

### ISSUE THREAD

**Issue by carystanley** [yahoo/routr#20]
The use of "reverend" in MakePath does not support having querystring params.

**Comment by lingyan** [comment]
Yup. reverend only generates path, not the query string.  But we can use `qs` to construct the query string param and tag it onto the path that's generated.

**Comment by celineotter** [comment]
@lingyan - please could you provide a brief example of how these two connect together ?

**Comment by lingyan** [comment]
Hi @celineotter,

routr no longer uese `reverend`.  It is now use `path-to-regexp` for `makePath` as well: https://github.com/yahoo/routr/blob/master/lib/router.js#L141-L165

`makePath` is the function used by `fluxible-router` to create the route's path in NavLink: https://github.com/yahoo/fluxible-router/blob/af15b8c3e2b9149824659c9cdb444c8b591e70de/lib/createNavLinkComponent.js#L91

So that application can provide `routeName` and `navParams` to `NavLink`, which will generate the href for the anchor using these 2 props.

This issue is a feature request for extending the makePath to be able to take also query params, and generate the href that contains both path and query string.

I hope this is what you meant by "how these two connect together" :)

**Comment by lingyan** [comment]
BTW, we can consider adding the support.  The tricky thing is depending on which query string library you use, the query string generated is actually different.  For example, between `qs` and node's built-in `querystring`:

```js
// qs_querystring.js
var qs = require('qs');
var querystring = require('querystring');

var k = {
    a: 1,
    b: false,
    c: {cc: 1},
    d: [1,2,3]
};
console.log('qs result=', qs.stringify(k));
console.log('querystring result=', querystring.stringify(k));
```
Running this simple script will output:
```bash
$ node qs_querystring.js 
qs result= a=1&b=false&c%5Bcc%5D=1&d%5B0%5D=1&d%5B1%5D=2&d%5B2%5D=3
querystring result= a=1&b=false&c=&d=1&d=2&d=3
```

**Comment by bchelli** [comment]
Hi Y'all,

:+1: for qs

This is a feature I really miss in routr and more especially in fluxible-router.
https://github.com/yahoo/fluxible-router/issues/74

Is anyone working on a pull request?

Thanks,
Ben

**Comment by redonkulus** [comment]
@bchelli no one is at the moment, if you would like to try it out and open a PR, that would be great!

**Comment by AaronLasseigne** [comment]
Instead of picking a library we could ask users to provide it in the constructor. It must provide a `stringify` function. If it is not provided and a user attempts to provide query parameters an error is thrown. If this sounds good I'm willing to work on a PR to implement it. Then of course a PR in `fluxible-router` to use the functionality there.
